apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Values.namespace }}
  type: Opaque
data:
  BROKER_PASSWORD: {{ .Values.rabbitmq.password| b64enc }}
  AWS_ACCESS_KEY_ID: {{ .Values.aws.accessKeyId| b64enc }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.aws.secretAccessKey| b64enc }}
  AWS_SESSION_TOKEN: {{ .Values.aws.sessionToken| b64enc }}